### ISSUE TITLE
text in charlists is not replace

### ISSUE THREAD

**Issue by danturn** [localvore-today/secure_log_formatter#12]
The erlang error logger gives us the text as a charlist so my regex is  not correctly applied to it
in this example the elixir Logger correctly redacts the password but the error loggers output is not redacted

iex(1)> require Logger; Logger.error "password: \"secret\""
14:09:55.353 [error] password: [REDACTED]
iex(2)> :error_logger.error_msg "password: \"secret\""
14:10:13.134 [error] password: "secret"

i've fixed this as part of PR #11 

dan

**Comment by doomspork** [comment]
Closed via #11
