### ISSUE TITLE
[request] make the sanitize function public

### ISSUE THREAD

**Issue by stephenmoloney** [localvore-today/secure_log_formatter#2]
Hi there,

I have a potential use case for this library to be optionally incorporate into [Og](https://hex.pm/packages/og) and two possible ways of doing it.

1. The ideal approach would be where `sanitize/1` functions are made public and docless perhaps in your library and then I can invoke them where I please in [Og](https://hex.pm/packages/og).

2. The less desirable approach is to apply the inspect function from SecureLogFormatter directly - because i was hoping to sanitize and then apply an option of different formatters.

This might not suit you though & I'll totally understand if it's :-1: .. I can probably work with option 2. if needs be.

Let me know what you think.

**Comment by doomspork** [comment]
Howdy @stephenmoloney and thanks for your interest!  I'd be open to doing this, let me take some time today to look over the possible changes and get back to you 😀

**Comment by weaktyper** [comment]
@doomspork 
This is how it will look no my side... 
`https://github.com/stephenmoloney/og/tree/sanitize#configuration-options`
I just add an option to `sanitize` and it will apply all the goodness from your lib. 😄

**Comment by doomspork** [comment]
Hot diggity!  If you're happy with this change I'll go ahead and merge this and push to hex.

**Comment by weaktyper** [comment]
closed by #3 

Many thanks... I'll be integrating this into `Og`

**Comment by stephenmoloney** [comment]
@doomspork
This is how it will look no my side...
https://github.com/stephenmoloney/og/tree/sanitize#configuration-options
I just add an option to sanitize and it will apply all the goodness from your lib. 😄

**Comment by stephenmoloney** [comment]
Many thanks... I'll integrate this into `Og`

**Comment by stephenmoloney** [comment]
@doomspork 
That looks perfect... wow, what a fast response time.. hard to beat.


💯
