### ISSUE TITLE
handle_sasl_reports: true causes errors

### ISSUE THREAD

**Issue by danturn** [localvore-today/secure_log_formatter#7]
Hi

i noticed today that if you have handle_sasl_reports set to true you get some errors.

It seems to be do to with structures like this:  [1,2 | 3] which although is a list, cannot be enumerated over!

SecureLogFormatter.sanitize([1,2|3])

 ** (FunctionClauseError) no function clause matching in Enum."-map/2-lists^map/1-0-"/2
     stacktrace:
       (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"(#Function<2.12591307/1 in SecureLogFormatter.sanitize/1>, 3)
       (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
       (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
       test/secure_log_formatter_test.exs:22: (test)

**Comment by doomspork** [comment]
Good find @danturn!
